config/routes.rb
Rails.application.routes.draw do
devise_for :users,
  :controllers => { :registrations => "registrations",
    :omniauth_callbacks => "omniauth_callbacks",
    :confirmations => "confirmations" }
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy', :method => :delete
    get 'sign_up' => 'devise/registrations#new'
    get 'signup' => 'devise/registrations#new'
    get '/confirm_email' => 'users#send_confirmation_link'
  end

  root :to => 'static_pages#home'
  get 'home' => 'static_pages#home'
  post 'thank_you' => 'static_pages#send_feedback'
  post 'suggestion' => 'static_pages#suggestion'
  get 'students' => 'users#index'
  get 'about' => "static_pages#about"
  get 'faq' => "static_pages#faq"
  get 'contact' => "static_pages#contact"
  get 'getting_involved' => "static_pages#getting_involved"
  get 'contributing' => "static_pages#contributing"
  get 'legal' => "static_pages#legal"
  get 'cla' => "static_pages#cla"
  get 'tou' => "static_pages#tou"
  get 'press' => redirect('https://docs.google.com/document/d/1FmjfYvOsQ-syoOCzuvPXv96TCxeJAT9m-Wl7trgNZcE/pub')
  get 'sitemap' => 'sitemap#index', :defaults => { :format => 'xml' }

  #failure route if github information returns invalid
  get '/auth/failure' => 'omniauth_callbacks#failure'

  resources :users, :only => [:show, :index, :edit, :update]

  # ***** COURSES AND LESSONS ROUTES *****
  # deprecated /courses/curriculum route redirect
  get '/courses/curriculum' => redirect('/courses')

  resources :courses, only: [:index, :show ] do
    resources :lessons, only: [:show]
  end
  resources :lessons, only: [:show] do
    resources :projects, only: [:create, :update, :destroy]

    get 'all_submissions', to: 'projects#all_submissions'
    get 'recent_submissions', to: 'projects#recent_submissions'
  end

  post 'lesson_completions' => 'lesson_completions#create'
  delete 'lesson_completions/:lesson_id' => 'lesson_completions#destroy', :as => 'lesson_completion'

  # Explicitly redirect deprecated routes (301)

  get 'curriculum' => redirect('/courses')
  get 'scheduler' => redirect('/courses')
  get ':course_name' => redirect('/courses/%{course_name}')
  get ':course_name/:lesson_name' => redirect('courses/%{course_name}/lessons/%{lesson_name}')
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @navbar = false
    @is_home_page = true
  end

  def about
  end

  def getting_involved
  end

  def legal
  end

  def tou
  end

  def cla
  end

  def suggestion
    if suggestion_body_not_empty?
      ContactMailer.suggestion_email(
        suggestion_body,
        current_page,
        user_identifier
      ).deliver_now
    end

    respond_to do |format|
      format.json { render json: suggestion_body }
    end
  end

  private

  def user_identifier
    current_user_email || 'Anonymous'
  end

  def current_user_email
    (current_user && current_user.email)
  end

  def current_page
    params[:pathname]
  end

  def suggestion_body
    @suggestion_body ||= params[:suggestion]
  end

  def suggestion_body_not_empty?
    !suggestion_body.empty?
  end
end

app/views/static_pages/about.html.erb
<div class="StaticPagesController">
  <div class="container">
    
    <h1>About The Odin Project</h1>
  
    <p>
      Learning to code on your own sucks.  It's time consuming, difficult to stay motivated, and lonely.  To top it all off, you usually don't even know if you're learning the right stuff, whether the goal is to build the website you want, start a startup, or get a job as a web developer.
    </p>

    <p>
      The Odin Project is one of those "What I wish I had when I was learning" resources.  Not everyone has access to a computer science education or the funds to attend an intensive coding school and neither of those is right for everyone anyway.  This project is designed to fill in the gap for people who are trying to hack it on their own but still want a high quality education.
    </p>

    <p>
      Because it's hard! It takes about 1,000 hours of work to go from zero to employable as a web developer.  The project aims to solve the biggest issues of that journey -- knowing what to learn and build and finding other students to learn with along the way.  
    </p>

    <h2>We Believe</h2>

    <ol>
      <li>
        <span class="belief-heading">You learn best by actually building things on your own computer</span> 
        <p>
          You can't just follow a bunch of online tutorials and expect to be a developer.  That's why we have a project-based curriculum that leaves you with a real portfolio of work on Github.
        </p>
      </li>
      <li>
        <span class="belief-heading">Education should be free and accessible to everyone</span> 
        <p>
          This curriculum itself is free and we tried to link to resources that are themselves free so anyone in the world can use them.
        </p>
      </li>
      <li>
        <span class="belief-heading">The best way to stay motivated is by working with other people</span>  
        <p>
          We're committed to connecting students together so they can stay motivated and learn faster.  Tools to do so are under development.
        </p>
      </li>
      <li>
        <span class="belief-heading">Open source is best</span>
        <p>
          Our curriculum is available on Github (under CC) and so is the source code for this website (under the MIT).  We encourage students and developers to contribute to both in an effort to make this even better.
        </p>
      </li>
    </ol>

    <h2>How it All Started</h2>

    <p>
      <a href="http://eriktrautman.com">Erik</a> decided it was time to learn web development in mid-2012 and immediately dove in with the fervor of an overmotivated geek tackling a new challenge.  
    </p>

    <p>
      He soon found that, though he was learning a lot of things very quickly, it didn't feel like he was getting much closer to his goal of becoming a functional web developer.  He also thought there was a whole lot missing from the experience of learning online, especially in terms of knowing which resources to use and being able to work with other people along the way.
    </p>

    <p>
      So he enrolled at an intensive coding bootcamp and got the chance to build projects with other students all day long for 9 weeks.  He liked the experience there so much that he decided to help them grow and improve their business for a while, but he was soon discouraged by seeing the sheer number of people who weren't able to take that same route and who were still out there struggling on their own.</p>

    <p>
      He decided that maybe it was possible to fix both of the problems he'd had before at the same time -- give people access to a free resource for learning to code AND help them find other beginners along the way.  If he could learn this stuff, he was determined to help others do the same.  Thus was born the Odin Project.
    </p>

    <p>
      The website is fully open source (<%= link_to "and students are currently helping to build it!", contributing_path %>) and the curriculum is freely available for noncommercial use.  Not just that, but this project is at the forefront of a powerful new movement to make software not just open source but also <em>Open Development</em> in order to make it as easy as possible for beginners to onboard to real life projects.  Every organizational meeting and most group coding sessions are <%= link_to "posted online", "https://plus.google.com/communities/100013596437379837846" %> and <%= link_to "recorded on YouTube", "https://www.youtube.com/channel/UCk0b0VTnJxXbxupXJ4D2yjQ" %>.  Check out our <%= link_to "Contributing Page", contributing_path %> to learn more and to see all the awesome people who have made significant contributions to the project.
    </p>
    <p>
      When lots of people help out, it means the project can stay current and meaningful to all future students who take its path.  It's a resource to everyone and a work in progress... so <%= link_to "please contribute!", contributing_path %>
    </p>

    <h2>Contact</h2>

    <p>
      If you have questions about The Odin Project itself, check out our <%= link_to "Contact Page", contact_path %>.
    </p>


  </div>
</div>

app/views/static_pages/cla.html.erb
<div class="StaticPagesController">
  <div class="container">

    <%= link_to "<< Back to Legal", legal_path %>

    <div id="cla">
      <% f = File.open("legal_cla.md", "rb") %>
      <%= convert_markdown_to_html(f.read) %>
      <% f.close %>
    </div>

  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="StaticPagesController">
  <div class="container">
    
    <h1>Contact Us</h1>
    <p><strong>Our directory is a bit complicated, so please pay attention:</strong></p>
    <p>If you'd like to get in touch, <em>please contact us <a href="mailto:contact@theodinproject.com">here.</em></a></p>
    <p>If you'd like to provide moral support, <em>please contact us <a href="mailto:contact@theodinproject.com">here.</em></a></p>
    <p>If you'd like to possibly contribute, <em>please visit the <%= link_to "contributing page", contributing_path %> or contact us <a href="mailto:contact@theodinproject.com">here</em></a>.</p>
    <p>If you've located dead links, typos or bugs and don't want to do a pull request, <em>please contact us <a href="mailto:contact@theodinproject.com">here.</em></a></p> 
    <p>If you'd like to vent your ire at how your life hasn't shaped up the way you hoped it would, <em>please contact us <a href="mailto:contact@theodinproject.com">here.</em></a></p>
    <p>If you'd like to rage and troll about the project itself, <em>please contact us <a href="mailto:contact@theodinproject.com">here.</em></a></p>
    <p>If you'd like to test out that new joke you learned, <em>please contact us <a href="mailto:contact@theodinproject.com">here.</em></a></p>
    <p>If you'd like to provide unsolicited advice, donations, or tips for good places to hike in the Bay Area, <em>please contact us <a href="mailto:contact@theodinproject.com">here.</em></a></p>
    <p>Else, what are you here for?</p>


  </div>
</div>

app/views/static_pages/faq.html.erb
<div class="StaticPagesController">
  <div class="container">
    
    <h1>Frequently Asked Questions</h1>
	  
    <h2 class="faq-question">Who is The Odin Project for?</h2>
    <p>
      The Odin Project is for absolute beginners and those who have tried other resources without success.  In reality, The Odin Project is for anyone who wants to work as a web developer, do freelancing work, build a startup, or just hack together a homepage for yourself.  All the tools you need are here.  
    </p>
    <p>
      We’ve built an in-depth curriculum designed to take you 100% of the way to becoming a web developer. Many other resources out there teach you just the basics of programming.  With The Odin Project you’ll create your own websites, games, and social media sites.
    </p>
    <p>
      The curriculum has also been designed in a modular fashion, making skimming through lessons a breeze.
    </p>



    <h2 class="faq-question">What is the goal of the The Odin Project?</h2>
    <p>
      The goal of The Odin Project is to provide a complete path for students to go from zero to employed as web developers while working with other students along the way.
    </p>



    <h2 class="faq-question">How long does The Odin Project take?</h2>
    <p>
      We won't have any of this "Learn it all in two days!" BS.  You can't start from scratch and learn true web development in such a short period of time and you know it.  It's highly unlikely that you'll be employable after a weekend workshop or a one-month part-time course.
    </p>
    <p>
      On the other hand, you don't necessarily need to put in 4 years getting a CS degree.  80% of what they cover won't be used during a typical web developer's early career and it's not necessary to get hired.  So why not learn the 20% and learn the rest while you're getting paid on the job?
    </p>
    <p>
      We've essentially distilled down what you most need to learn to hit that employable level, but it's still a healthy dose of learning.  Depending how fast you learn, it will take roughly 1000 hours of work to hit that sweet spot.  If you're naturally more technical or come from a technical background, it may be a bit faster.  If you're less technical or brand new to all this, it will take longer.  Don't despair!  When you think about it, that's pretty much the same learning curve you had to climb to learn anything worthwhile so far in life.
    </p>



    <h2 class="faq-question">What are you actually teaching?</h2>
    <p>
      The Odin Project assumes you’re new to web development, so we start out by going over what exactly a web developer does in our <%= link_to "Introduction to Web Development", course_path("introduction-to-web-development") %> course.
    </p>
    <p>
      The <%= link_to "Web Development 101 course", course_path("web-development-101") %> will give you a chance to explore several of the languages and technologies you’ll need to know on your journey to becoming a web developer.  Web Development 101 introduces HTML, CSS, Javascript, Ruby, Rails, Git, databases and more. We’ve also created mini-projects that give you a chance to test your new knowledge by building your own applications and websites!
    </p>
    <p>
      The Odin Project takes a back-to-front approach to learning Ruby on Rails.  We start with a <%= link_to "strong foundation in Ruby", course_path("ruby-programming") %> and an understanding of databases before migrating into <%= link_to "Ruby on Rails", course_path("ruby-on-rails") %> (which is a framework built using Ruby).
    </p>
    <p>
      The Odin Project then takes you deep into <%= link_to "HTML and CSS", course_path("html5-and-css3") %>, along with <%= link_to "Javascript, JQuery and Backbone", course_path("javascript-and-jquery") %> to give you all the tools necessary to make websites flow, load quickly, and look great.  Along the way you’ll learn Git and deployment so you can build your own portfolio, collaborate with others, and see your work on the web.
    </p>
    <p>
      Finally, The Odin Project will teach you to work with legacy codebases and open-source projects. We’ll also cover areas specifically intended to help when you’re <%= link_to "looking for employment", course_path("getting-hired-as-a-web-developer") %>.
    </p>



    <h2 class="faq-question">Why Ruby on Rails?</h2>
    <p>
      There are dozens of frameworks and technology stacks to choose from and, frankly, they do pretty much the same thing. Ruby on Rails is attractive because it’s straightforward and well documented.  It’s also used by many tech companies and has a strong community of developers who support it.
    </p>
    <p>
      Rails lets you deploy a functioning website in hours instead of weeks.  Rails also provides a great platform to build the skills you need to carry you to the next phase.
    </p>



    <h2 class="faq-question">Who is "Odin"?</h2>
    <p>
      Odin is a figure from Norse mythology, the allfather of the gods. He is portrayed as powerful and fickle (as they often are) but also wise and cunning. His search for knowledge is a thing of legends - he <%= link_to "gave his eye for the wisdom of ages", "http://norse-mythology.org/tales/why-odin-is-one-eyed/" %> and hung from the world tree, pierced by his own spear, for nine days and nights to <%= link_to "gain the knowledge of runes", "http://norse-mythology.org/tales/odins-discovery-of-the-runes/" %>.
    </p>
    <p>
      Learning development is not an easy task and the tools laid out here are merely the path; you must walk it yourself. Should you possess a thirst for knowledge and persistence of spirit akin to that storied in Odin's mythos, you will find success on your journey.
    </p>


    <h2 class="faq-question">Where do I sign up?</h2>
    <p>
      You don’t have to!  Dive right in, the content is free and available.  It’d be best if you started at the beginning and went through in order but everyone’s goals are different so we made the full curriculum available if you want to cherry-pick lessons or projects.
    </p>
    <p>
      However, by <%= link_to "signing up", new_user_registration_path %> you are able to check off completed projects and lessons, easily keeping track of your progress.  We don't collect any user data and keep emails to a minimum.
    </p>



    <h2 class="faq-question">Is The Odin Project free?</h2>
    <p>
      Yes! The Odin Project is an open-source project created and maintained by hard working volunteers. If you want to help please <%= link_to "reach out", contact_path %>.
    </p>


    <h2 class="faq-question">When do I pay?</h2>
    <p>
      You don't! The Odin Project is open-source and completely free.
    </p>
    <p>
      If you insist on compensation, you can donate your time to help those just starting The Odin Project or create a new feature for the site.
    </p>


    <h2 class="faq-question">How will The Odin Project become sustainable?</h2>
    <p>
      The Odin Project's business model is educating students.  Core content will always be free, but we'd also like to give students who want more structure and/or help on their journeys access to those services, which would be at a premium. If you want to help please <%= link_to "reach out", contact_path %>.
    </p>


    <h2 class="faq-question">Can I Use This Curriculum To Teach?</h2>
    <p>
      The Odin Project is licensed under two pieces: the curriculum and the main website.  The main website is a fully open-source project <a href="https://github.com/TheOdinProject/theodinproject/blob/master/license.txt">under an MIT license</a>, so you can use the code for whatever you want.  The curriculum is currently licensed under a <a href="https://github.com/TheOdinProject/curriculum/blob/master/license.md">Creative Commons license</a> which restricts it to noncommercial use without prior authorization. 
    </p>
    <p>
      This means you can use The Odin Project’s curriculum to teach at your club, meetup, or with your friends (In fact, we’d love it if you did that and told us how it went!). You can’t, however, use it to start a bootcamp without having a conversation first.  Please reach out with any questions to <a href="mailto: contact@theodinproject.com">contact@theodinproject.com</a>
    </p>



    <h2 class="faq-question">How can I get in touch?</h2>
    <p>
      If you have questions about The Odin Project itself, check out our <%= link_to "Contact Page", contact_path %>.  We also have a friendly Odin community in our <a href="https://gitter.im/TheOdinProject/theodinproject">Gitter chatrooms</a>
    </p>

  </div>
</div>

app/views/static_pages/home.html.erb
<div id="home-page">

  <div class="above-the-fold">
    <div class="shield">
      <div class="navbar">
        <div class="nav-narrow">
          <div class="logo-wrapper">
            <%= render :partial => "shared/logo_text" %>
          </div>
          <div class="menu-wrapper">
            <%= link_to "Curriculum", courses_path(:ref => "homenav") %> |
            <% if current_user %>
              <%= link_to "Logout", logout_path(:ref => "homenav") %>
            <% else %>
              <%= link_to "Login", login_path(:ref => "homenav")%>
            <% end %>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
      <div class="container narrow">
        <div class="top-box-wrapper">
          <div class="top-box">
            <div class="headline">
              <h1>
                Learn Web Development for Free
              </h1>
            </div>
            <div class="subheading">
              <h2>
                Stop wasting time...&nbsp;  Here's what you need to know.
              </h2>
            </div>
          </div>
        </div>

        <div class="cta-box-top-wrapper">
          <div class="cta-box-top">
            <a href='courses/introduction-to-web-development/lessons/what-a-web-developer-does'>
              <button class="btn btn-success cta-button">
                Learn what a web developer does
              </button>
            </a>
            <%= link_to courses_path(:ref => "home") do %>
              <button class="btn btn-success cta-button">
                Explore the full curriculum
              </button>
            <% end %>
            <p>
              ...or scroll down to learn more
            </p>
          </div>
        </div>

      </div>
    </div>
  </div>


  <div class="social-buttons">
    <div class="container narrow">
      <%= render "shared/social" %>
    </div>
  </div>

  <div class="what-its-about section">
    <div class="container narrow">

      <h2>Okay, what's this all about?</h2>
      <h4>
        Basically, this is the website we wish we'd had when we were learning on our own.  So we stitched together a curriculum from the best resources we could find online and here it is. This project is about:
      </h4>

      <div class="about-panels">

        <div class="about-panel">
          <div class="img-wrapper">
            <%= image_tag "icons/compass2.png", :width => "100px", :title => "A Path Forward" %>
          </div>
          <h3>
            Having a Path
          </h3>
          <p>
            This is a proven path to successfully learn web development so you don't have to wonder if you're doing the right stuff or wasting your time.
          </p>
        </div>

        <div class="about-panel">
          <div class="img-wrapper">
            <%= image_tag "icons/portfolio2.png", :width => "100px", :title => "Building a Portfolio" %>
          </div>
          <h3>
            Building a Portfolio
          </h3>
          <p>
            The best way to learn and get hired is to have a portfolio of work so we've laid out great projects to build along the way
          </p>
        </div>

        <div class="about-panel">
          <div class="img-wrapper">
            <%= image_tag "icons/chat.png", :width => "100px", :title => "Learning Together" %>
          </div>
          <h3>
            Learning Together
          </h3>
          <p>
            We make it easy to find and work with other learners so you don't have to go it alone anymore.
          </p>
        </div>

        <div class="clearfix"></div>

      </div>
    </div>
  </div>


  <div class="what-youll-learn dark">
    <div class="section">

      <div class="container narrow">

        <h2>
          What You'll Learn
        </h2>

        <div class="course-panels">

          <a href="<%= course_path('introduction-to-web-development') %>">
            <div class="course-panel p1">
              <div class="img-wrapper">
                <%= image_tag "icons/play.png", :width => "80px", :title => "Introduction to Web Development" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Introduction to Web Development
                </h3>
                <p>
                  A brief introduction to the practice and career of web development
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('web-development-101') %>">
            <div class="course-panel p2">
              <div class="img-wrapper">
                <%= image_tag "icons/web_development.png", :width => "80px", :title => "Web Development" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Web Development 101
                </h3>
                <p>
                  Learn the basics of all the technologies you need to build websites
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('ruby-programming') %>">
            <div class="course-panel p3">
              <div class="img-wrapper">
                <%= image_tag "icons/ruby.png", :width => "65px", :title => "Ruby Programming" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Ruby Programming
                </h3>
                <p>
                  Learn programming fundamentals in Ruby, the language built for programmer happiness
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('ruby-on-rails') %>">
            <div class="course-panel p4">
              <div class="img-wrapper">
                <%= image_tag "icons/rails.png", :width => "80px", :title => "Ruby on Rails" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Ruby on Rails
                </h3>
                <p>
                  Learn to rapidly develop and deploy websites using Ruby on Rails
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('html5-and-css3') %>">
            <div class="course-panel p5">
              <div class="img-wrapper">
                <%= image_tag "icons/html5.png", :width => "80px", :title => "HTML5 and CSS3" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  HTML5 and CSS3
                </h3>
                <p>
                  Dive deeper and understand how to really make your websites look good
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('javascript-and-jquery') %>">
            <div class="course-panel p6">
              <div class="img-wrapper">
                <%= image_tag "icons/javascript2.png", :width => "80px", :title => "Javascript and jQuery" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Javascript and jQuery
                </h3>
                <p>
                  Make your websites dynamic and smooth with Javascript and jQuery
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('getting-hired-as-a-web-developer') %>">
            <div class="course-panel p7">
              <div class="img-wrapper">
                <%= image_tag "icons/job_button2.png", :width => "80px", :title => "Getting Hired as a Web Developer" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Getting Hired as a Web Developer
                </h3>
                <p>
                  You've got the skills and the portfolio, now how do you get the job?
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="how-it-works section">
    <div class="container narrow">
      <h2>How it Works</h2>
      <div class="clearfix"></div>
      <div class="panel-wrapper">
        <div class="panel">
          <div class="img-wrapper">
            <%= image_tag "learn_online3.jpg", :width => "300px", :height => "150px", :title => "Learn to Code" %>
          </div>
          <h3>
            Learn
          </h3>
          <p>
            We'll guide you through the best videos, tutorials, blog posts, and courses on the web for learning each subject.
          </p>
        </div>

        <div class="panel">
          <div class="img-wrapper">
            <%= image_tag "writing_code2.jpg", :width => "300px", :height => "150px", :title => "Write Code" %>
          </div>
          <h3>
            Build
          </h3>
          <p>
            You will build dozens of projects along the way, from simple scripts to full programs and deployed websites
          </p>
        </div>

      </div>

      <div class="work-together">
        <div class="img-wrapper">
            <%= image_tag "work_together_blur.jpg", :width => "500px", :height => "200px", :title => "Work Together" %>
        </div>
        <div class="copy-wrapper">
          <h3>
            Work with Other Students
          </h3>
          <p>
            Learning on your own sucks (we've been there).  We're building tools to connect you with other students along the way so you can pair up on the projects or just work through those annoying bugs with someone else across the world.
          </p>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

  <div class="why-awesome section dark">
    <div class="container narrow">
      <h2>
        Why This Project Rocks
      </h2>
      <div class="panel-wrapper">
        <div class="panel">
          <div class="img-wrapper">
            <%= image_tag "icons/textedit.png", :width => "150px", :title => "A Living Curriculum" %>
          </div>
          <h3>
            The Curriculum Lives
          </h3>
          <p>
            The curriculum is really flexible -- when a better way to learn something comes along we can just use that instead!
          </p>
          <a href="https://github.com/TheOdinProject/curriculum">See the curriculum on Github >></a>
        </div>

        <div class="panel">
          <div class="img-wrapper">
            <%= image_tag "icons/open_source2.svg", :width => "150px", :title => "Open Source" %>
          </div>
          <h3>
            It's Open Source
          </h3>
          <p>
            This website is available under an MIT license and the curriculum is Creative Commons.  Both are on Github.          </p>
          <a href="https://github.com/TheOdinProject/theodinproject">See this site on Github >></a>
        </div>

        <div class="panel">
          <div class="img-wrapper">
            <%= image_tag "icons/xcode.png", :width => "150px", :title => "Build You Own Tools" %>
          </div>
          <h3>
            Build Your Own Tools
          </h3>
          <p>
            Students are currently contributing to both the curriculum and the main website... so they build what they use.
          </p>
          <%= link_to "Learn how to contribute >>", contributing_path %>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

    <div class="clear-div"></div>

  <div class="cta-bottom section">
    <div class="container narrow">
      <p>
        Are you curious yet?
      </p>
      <%= link_to courses_path(:ref => "home_b") do %>
        <button class="btn btn-success cta-button">
          Check out the curriculum!
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/legal.html.erb
<div class="StaticPagesController">
  <div class="container">
    
    <h1>Legal Stuff</h1>

    <p>...Because otherwise what would we do with all the lawyers?!?</p>

    <%= link_to tou_path do %>
      <h2>Terms of Use</h2>
    <% end %>
    <p>
      These Terms of Use govern your use of the website.
    </p>


    <%= link_to cla_path do %>
      <h2>Contributor Licensing Agreement (CLA)</h2>
    <% end %>
    <p>
      This agreement applies when you make contributions to this website.  For details about contributions to the Curriculum, refer to the <%= link_to "Contributing section", contributing_path %>.
    </p>

  </div>
</div>