config/routes.rb
Rails.application.routes.draw do
devise_for :users,
  :controllers => { :registrations => "registrations",
    :omniauth_callbacks => "omniauth_callbacks",
    :confirmations => "confirmations" }
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy', :method => :delete
    get 'sign_up' => 'devise/registrations#new'
    get 'signup' => 'devise/registrations#new'
    get '/confirm_email' => 'users#send_confirmation_link'
  end

  root :to => 'static_pages#home'
  get 'home' => 'static_pages#home'
  post 'thank_you' => 'static_pages#send_feedback'
  post 'suggestion' => 'static_pages#suggestion'
  get 'students' => 'users#index'
  get 'about' => "static_pages#about"
  get 'faq' => "static_pages#faq"
  get 'contact' => "static_pages#contact"
  get 'getting_involved' => "static_pages#getting_involved"
  get 'contributing' => "static_pages#contributing"
  get 'legal' => "static_pages#legal"
  get 'cla' => "static_pages#cla"
  get 'tou' => "static_pages#tou"
  get 'press' => redirect('https://docs.google.com/document/d/1FmjfYvOsQ-syoOCzuvPXv96TCxeJAT9m-Wl7trgNZcE/pub')
  get 'sitemap' => 'sitemap#index', :defaults => { :format => 'xml' }

  #failure route if github information returns invalid
  get '/auth/failure' => 'omniauth_callbacks#failure'

  resources :users, :only => [:show, :index, :edit, :update]

  # ***** COURSES AND LESSONS ROUTES *****
  # deprecated /courses/curriculum route redirect
  get '/courses/curriculum' => redirect('/courses')

  resources :courses, only: [:index, :show ] do
    resources :lessons, only: [:show]
  end
  resources :lessons, only: [:show] do
    resources :projects, only: [:create, :update, :destroy]

    get 'all_submissions', to: 'projects#all_submissions'
    get 'recent_submissions', to: 'projects#recent_submissions'
  end

  post 'lesson_completions' => 'lesson_completions#create'
  delete 'lesson_completions/:lesson_id' => 'lesson_completions#destroy', :as => 'lesson_completion'

  # Explicitly redirect deprecated routes (301)

  get 'curriculum' => redirect('/courses')
  get 'scheduler' => redirect('/courses')
  get ':course_name' => redirect('/courses/%{course_name}')
  get ':course_name/:lesson_name' => redirect('courses/%{course_name}/lessons/%{lesson_name}')
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates_uniqueness_of :username, :email
  validates_presence_of :legal_agreement, message: "Don't forget the legal stuff!", on: :create
  validates :username, length: { in: 4..20 }

  has_many :lesson_completions, foreign_key: :student_id
  has_many :completed_lessons, through: :lesson_completions, source: :lesson
  has_many :projects

  def self.by_latest_completion
    User.left_outer_joins(:lesson_completions)
        .select('max(lesson_completions.created_at) as latest_completion_date, users.*')
        .group('users.id')
        .order('latest_completion_date desc nulls last')
  end

  def completed_lesson?(lesson)
    completed_lessons.exists?(lesson.id)
  end

  def latest_completed_lesson
    return unless last_lesson_completed
    Lesson.find(last_lesson_completed.lesson_id)
  end

  def lesson_completion_time(lesson)
    lesson_completions.find_by(lesson_id: lesson.id).created_at
  end

  def last_lesson_completed
    ordered_lesson_completions.last
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid).to_hash).first_or_create(
      provider: auth[:provider],
      uid: auth[:uid],
      username: auth[:info][:name],
      email: auth[:info][:email]
    )
  end

  def add_omniauth(auth)
    self.provider ||= auth['provider']
    self.uid ||= auth['uid']
    save
    self
  end

  def password_required?
    super && provider.blank?
  end

  def send_confirmation_instructions
    generate_confirmation_token! unless @raw_confirmation_token
    send_welcome_email(@raw_confirmation_token)
  end

  private

  def ordered_lesson_completions
    lesson_completions.order(created_at: :asc)
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new(session['devise.user_attributes']) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def send_welcome_email(token)
    UserMailer.send_welcome_email_to(self, token).deliver_now!
  rescue => error
    logger.error "Error sending welcome email: #{error}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: [:index, :send_confirmation_link]
  before_action :authenticate_user!
  authorize_resource only: [:edit, :update]

  def show
  end

  def edit
    @edit = true
    render :show
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Your profile was updated successfully'
      redirect_to @user
    else
      flash.now[:error] = "We could not update your profile. Errors: #{@user.errors.full_messages}"
      render :show
    end
  end

  def index
    @users = users_by_latest_lesson_completion
  end

  def send_confirmation_link
    current_user.send_confirmation_instructions
    flash[:notice] = 'Confirmation instructions have been sent to your email address!'
    redirect_to request.referer
  end

  private

  def user_params
    params
      .require(:user)
      .permit(
        :email,
        :username,
        :password,
        :password_confirmation,
        :legal_agreement,
        :skype,
        :screenhero,
        :facebook,
        :twitter,
        :linkedin,
        :github,
        :google_plus,
        :about,
        :uid,
        :provider,
      )
  end

  def find_user
    @user = UserDecorator.new(user)
  end

  def user
    User.find(params[:id])
  end

  def users_by_latest_lesson_completion
    User.by_latest_completion.paginate(page: params[:page], per_page: 15)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_url(user, size)
    GravatarUrlBuilder.new(user, size).url
  end

  def lesson_time(user, lesson)
    user.lesson_completion_time(lesson).to_formatted_s(:long)
  end
end

app/views/users/_user.html.erb
<div class="row student">
  <div class="student-pic">
    <a href="<%= user_path(user) %>">
      <img src="<%= gravatar_url(user, 100) %>" title="<%= user.username %>" class="student-mini-pic">
    </a>
  </div>
  <div class="student-info">
    <h3><%= link_to "#{user.username}", user %></h3>
    <% lesson = user.latest_completed_lesson %>
    <% if lesson %>
      <em>
        Completed
        "<%= link_to "#{lesson.course.title}: #{lesson.title}", lesson_path(lesson.id) %>" <%= distance_of_time_in_words(Time.now - user.last_lesson_completed.created_at) %> ago
      </em>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="span8 offset2">
      <h2>Students</h2>
      <div id="students-list">
        <% @users.each do |user| %>
          <%= render user %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render :partial => "shared/pagination", :locals => {:collection => @users }%>

app/views/users/show.html.erb
<div id="profile-page" class="container">
  <% if @edit %>
    <form accept-charset="UTF-8" id="edit-user" method="post" action="/users/<%= @user.id %>">
      <input name="_method" type="hidden" value="put">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  <% end %>

  <div class="row">

    <div class="span3 offset1">
      <div class="profile-photo-container">
        <img src="<%= gravatar_url(@user, 270) %>">
        <% if @edit %>
          <%= link_to "Edit your Gravatar image", "https://en.gravatar.com/site/login", :class => "edit-gravatar", :target => "_blank", :title => "Go to Gravatar.com to edit your profile image.  Gravatar lets you change your profile photo in just one place (their site) and then it's available to any other site that links to it (which is a lot of them). That way, when you want to change your photo later, you don't need to track it down on a dozen different websites. Cool!" %>
        <% end %>
      </div>
    </div>

    <div class="span6">
      <h2 class="profile-headline"><%= @user.username %>'s Profile</h2>
      <% if @user == current_user %>
        <% if @edit %>
          <input type="submit" class="btn btn-medium btn-primary edit-profile" value="Update" >
      <%= link_to "Cancel", @user, :class => "edit-profile btn btn-medium btn-warning" %>
        <% else %>
          <a href="<%= edit_user_path(current_user) %>"><button class='edit-profile btn btn-medium btn-primary'>Edit Profile</button></a>
        <% end %>
      <% end %>
      <div class="providers-button-container">
        <% if @user == current_user && @user.provider.nil? %>
          <%- User.omniauth_providers.each do |provider| %>
            <%= link_to "<i class=\"fa fa-#{provider} providers-button\"></i>Link your #{provider.to_s.titleize} account".html_safe, omniauth_authorize_path(:user, :github), id: 'github-link', class: 'btn btn-social btn-large btn-lg btn-github' %><br />
          <% end -%>
        <% end %>
      </div>
      <% if !@user.about.blank? or @edit %>
        <h3>About</h3>
        <div class="profile-about">
          <% if @edit %>
            <textarea id="user_about" name="user[about]" cols="70" rows="8" placeholder="Tell us about yourself!"><%= @user.about %></textarea>
          <% else %>
            <p>
              <%= @user.about %>
            </p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="span3 offset1">
      <div class="profile-contact-links">
        <% if @edit %>
          <ul>
            <li><input type="text" id="user_skype" name="user[skype]" size="50" placeholder="Skype username..." value="<%= @user.skype %>"></li>
            <li><input type="text" id="user_screenhero" name="user[screenhero]" size="50" placeholder="ScreenHero username..." value="<%= @user.screenhero %>"></li>
            <li><hr></li>
            <li><input type="text" id="user_google_plus" name="user[google_plus]" size="50" placeholder="Google Plus URL..." value="<%= @user.google_plus %>"></li>
            <li><input type="text" id="user_github" name="user[github]" size="50" placeholder="Github username..." value="<%= @user.github %>"></li>
            <li><input type="text" id="user_twitter" name="user[twitter]" size="50" placeholder="Twitter handle..." value="<%= @user.twitter %>"></li>
            <li><input type="text" id="user_facebook" name="user[facebook]" size="50" placeholder="Facebook username..." value="<%= @user.facebook %>"></li>
            <li><input type="text" id="user_linkedin" name="user[linkedin]" size="50" placeholder="LinkedIn username..." value="<%= @user.linkedin %>"></li>
          </ul>

        <% else %>

          <ul>
            <% if !@user.skype.blank? %>
            <li>
              Skype: <%= @user.skype %>
            </li>
            <% end %>

            <% if !@user.screenhero.blank? %>
            <li>
              ScreenHero:  <%= @user.screenhero %>
            </li>
            <% end %>
            <li><hr></li>

        </ul>
        <ul class="social-links">
          <% if !@user.google_plus.blank? %>
            <li>
              <%= link_to @user.google_plus do %>
              <i class="fa fa-google-plus"></i>
              <% end %>
            </li>
            <% end %>

            <% if !@user.github.blank? %>
            <li>
              <%= link_to @user.github_url do %>
              <i class="fa fa-github"></i>
              <% end %>
            </li>
            <% end %>

            <% if !@user.twitter .blank? %>
            <li>
              <%= link_to @user.twitter_url do%>
              <i class="fa fa-twitter"></i>
              <% end %>
            </li>
            <% end %>

            <% if !@user.facebook.blank? %>
            <li>
              <%= link_to @user.facebook_url do %>
              <i class="fa fa-facebook-square"></i>
              <% end %>
            </li>
            <% end %>

            <% if !@user.linkedin.blank? %>
            <li>
              <%= link_to @user.linkedin_url do%>
              <i class="fa fa-linkedin"></i>
              <% end %>
            </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>

    <% if !@user.completed_lessons.blank?%>
    <div class="span6">
      <div class="profile-projects">
        <h3>Completed Lessons: <%= @user.completed_lessons.count %></h3>
        <ul>
          <% @user.completed_lessons.each do |lesson| %>
            <li><i class="fa fa-check"></i> <%= link_to("#{lesson.course.title}:  #{lesson.title}", lesson_path(lesson.id)) %>
              <p>Completed: <%= lesson_time(@user, lesson) %> UTC</p>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
    <% end %>
    <% if @edit %>
      </form>
    <% end %>

  </div>

</div>